on:
  workflow_dispatch:
    inputs:
      dispatch_token:
        description: 'Token that authorize the dispatch'
        required: true
      head_sha:
        description: 'Head commit SHA that dispatched the workflow'
        required: true
      pr_author_username:
        description: 'Pull Request author username'
        required: true
      pr_number:
        description: 'Pull Request number that dispatched the workflow'
        required: true

jobs:
  evaluator:
    runs-on: self-hosted
    steps:
      - name: Fetch project repository
        uses: actions/checkout@v2

      - name: Fetch ESLint evaluator
        uses: actions/checkout@v2
        with:
          repository: betrybe/eslint-linter-action
          ref: v3
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/eslint-evaluator

      - name: Fetch Stylelint evaluator
        uses: actions/checkout@v2
        with:
          repository: betrybe/stylelint-linter-action
          ref: v2.1
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/stylelint-evaluator

      - name: Fetch Blocked Files Checkout action
        uses: actions/checkout@v2
        with:
          repository: betrybe/blocked-files-checkout-action
          ref: v2
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/blocked-files-checkout

      - name: Fetch Cypress evaluator
        uses: actions/checkout@v2
        with:
          repository: betrybe/cypress-evaluator-action
          ref: v7
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/cypress-evaluator

      - name: Fetch Store evaluation
        uses: actions/checkout@v2
        with:
          repository: betrybe/store-evaluation-action
          ref: v4
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/store-evaluation

      - name: Setup NodeJS
        uses: actions/setup-node@v1.4.4
        with:
          node-version: '16'

      - name: Restore protected files
        uses: ./.github/actions/blocked-files-checkout
        with:
          restore_branch: 'master'

      - name: Run ESLint evaluator
        uses: ./.github/actions/eslint-evaluator
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.inputs.pr_number }}

      - name: Run StyleLint evaluator
        uses: ./.github/actions/stylelint-evaluator
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.inputs.pr_number }}

      - name: Run Cypress evaluator
        id: evaluator
        uses: ./.github/actions/cypress-evaluator
        with:
          pr_author_username: ${{ github.event.inputs.pr_author_username }}
          npm-start: true

      - name: Run Store evaluation
        uses: ./.github/actions/store-evaluation
        with:
          evaluation-data: ${{ steps.evaluator.outputs.result }}
          environment: production
          pr-number: ${{ github.event.inputs.pr_number }}